#这是帮助您开始行动的基本工作流程

名字: 名称:CI

#控制工作流运行的时间
在:
#在推或拉请求事件时触发工作流,但仅限于"主"分支#在推或拉请求事件时触发工作流，但仅限于“主”分支
推:
分支: [分支:[ "主要" ]"主要" ]
拉取请求:
分支: [分支:[ "主要" ]"主要" ]

#允许您从"操作"选项卡手动运行此工作流#允许您从“操作”选项卡手动运行此工作流
工作流_调度:

#工作流运行由一个或多个可以顺序或并行运行的作业组成
工作:
#此工作流包含一个名为"构建"的作业#此工作流包含一个名为“构建”的作业
建设:
#将运行作业的运行程序的类型#将运行作业的运行程序的类型
连续运行: 运行:Ubuntu-最新版

#步骤表示将作为作业的一部分执行的一系列任务#步骤表示将作为作业的一部分执行的一系列任务
步伐:
#签出GITHUB _ WORKSPACE下的存储库,以便您的作业可以访问它#签出GITHUB _ WORKSPACE下的存储库，以便您的作业可以访问它
      - 使用: - uses: actions/checkout@v4

      #使用runners shell运行单个命令
      - 名字: 运行一行脚本
奔跑: 回声你好，世界！

      #使用runners shell运行一组命令
      - 名字: 运行多行脚本
奔跑: |
echo添加其他动作来构建，
          echo test, and deploy your project.
